---
title: 'HW2'
author: 'John Koo'
# output: pdf_document
output: html_document
# geometry: "left=1cm,right=1cm,top=1cm,bottom=1.5cm"
urlcolor: blue
header-includes:
- \usepackage{float}
- \usepackage{mathtools}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      comment = NA, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.pos = 'H', 
                      fig.align = 'center', 
                      fig.height = 2, 
                      fig.width = 4, 
                      fig.dpi = 300)

options(xtable.comment = FALSE, 
        xtable.table.placement = 'H')
```

# 3.1

```{r}
rosenbrock <- function(x) {
  100 * (x[2] - x[1] ** 2) ** 2 + (1 - x[1]) ** 2
}

rosenbrock.grad <- function(x) {
  c(400 * x[1] * (x[1] ** 2 - x[2]) + 2 * (x[1] - 1),
    200 * (x[2] - x[1] ** 2))
}

rosenbrock.hess <- function(x) {
  matrix(c(400 * (3 * x[1] ** 2 - x[2]) + 2, 
           -400 * x[1],
           -400 * x[1],
           200),
         nrow = 2, ncol = 2)
}

backtrack <- function(fn, grad.fn, hess.fn, 
                      x.start, 
                      method = 'newton', 
                      alpha = 1, rho = .5, c. = .5,
                      eps = 1e-9,
                      maxit = 1000) {
  x <- x.start
  x.prev <- x + 1
  iter <- 0
  while (sum(grad.fn(x) ** 2) > eps) {
    iter <- iter + 1
    x.prev <- x
    a <- alpha
    grad <- grad.fn(x)
    if (method == 'newton') {
      hess <- hess.fn(x)
      p <- -as.numeric(solve(hess) %*% grad)
    } else {
      p <- -grad
    }
    while (fn(x + a * p) > fn(x) + c. * a * as.numeric(t(grad) %*% p)) {
      a <- rho * a
    }
    print(paste('step length:', a))
    x <- x + a * p
    print(paste('current point:', x))
    if (iter > maxit) {
      warning('failed to converge')
      break
    }
  }
  return(x)
}
```

```{r}
x <- backtrack(rosenbrock, rosenbrock.grad, rosenbrock.hess, c(1.2, 1.2))
x <- backtrack(rosenbrock, rosenbrock.grad, rosenbrock.hess, c(-1.2, 1))

x <- backtrack(rosenbrock, rosenbrock.grad, rosenbrock.hess, c(1.2, 1.2),
               method = 'steepest descent')
x <- backtrack(rosenbrock, rosenbrock.grad, rosenbrock.hess, c(-1.2, 1),
               method = 'steepest descent')
```