// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// search_algo
Rcpp::List search_algo(const arma::vec& y, const arma::mat& X_covariates);
RcppExport SEXP _Stat676pack_search_algo(SEXP ySEXP, SEXP X_covariatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_covariates(X_covariatesSEXP);
    rcpp_result_gen = Rcpp::wrap(search_algo(y, X_covariates));
    return rcpp_result_gen;
END_RCPP
}
// lm_mcmc_horseshoe
Rcpp::List lm_mcmc_horseshoe(const arma::vec& y, const arma::mat& X_covariates, const unsigned int& N_sims, const unsigned long int& seed);
RcppExport SEXP _Stat676pack_lm_mcmc_horseshoe(SEXP ySEXP, SEXP X_covariatesSEXP, SEXP N_simsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_covariates(X_covariatesSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type N_sims(N_simsSEXP);
    Rcpp::traits::input_parameter< const unsigned long int& >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_mcmc_horseshoe(y, X_covariates, N_sims, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Stat676pack_search_algo", (DL_FUNC) &_Stat676pack_search_algo, 2},
    {"_Stat676pack_lm_mcmc_horseshoe", (DL_FUNC) &_Stat676pack_lm_mcmc_horseshoe, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Stat676pack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
