---
title: "MATH-M463"
subtitle: 'Homework 6'
author: "John Koo"
output: pdf_document
# output: html_document
header-includes:
- \usepackage{float}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      comment = NA, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.pos = 'H', 
                      fig.align = 'center')
options(xtable.comment = FALSE, 
        xtable.table.placement = 'H')
```

# Problem 1

$p = \frac{1}{6}$, $q = \frac{5}{6}$

## Part a

Let's say that the third player wins on the first try. The probability of this 
is $q^2 p$. Similarly, the probably of the third player winning on the second 
try is $q^5 p$, third try is $q^8 p$, i^th^ try is $q^{3i - 1} p$. So 
$P(\text{third player wins}) = \sum_{i = 1} q^{3i - 1} p$ 
$= p \sum_{i = 0} q^{3i + 2}$
$= pq^2 \sum_{i = 0} q^{3i} = \frac{pq^2}{1 - q^3} = \boxed{\frac{25}{91}}$

## Part b

Similar to part (a), the probably of the second player winning on the i^th^ try 
is just $pq^{3i - 2}$, so $P(\text{second player wins})$ 
$= pq \sum_{i = 0} q^{3i} = \frac{pq}{1 - q^3} = \boxed{\frac{30}{91}}$

## Part c

Similar to parts (a) and (b), the probability of the first player winning on the 
i^th^ try is $p q^{3i - 3}$, so $P(\text{first player wins})$
$= p \sum_{i = 0} q^{3i} = \frac{p}{1 - q^3} = \boxed{\frac{36}{91}}$

# Problem 2

Let $W = \frac{X Y}{Y} = X$. Since $W$ is a function of $X$ and $Y$ but not $Z$ 
and $X$ and $Y$ are independent of $Z$, $W$ is independent of $Z$. But $W$ is 
just $X$, so $X$ and $Z$ are pairwise independent. The same goes for the other 
two pairs by symmetry.

# Problem 3

Let $W = X + Y + Z$. Then $E[W] = E[X] + E[Y] + E[Z]$.

For brevity, denote the respective expected values by $\mu_X$, $\mu_Y$, and 
$\mu_Z$.

Consider $(W - E[W]) ^ 2$:

$$(W - E[W]) ^ 2 = ((X - \mu_X) + (Y - \mu_Y) + (Z - \mu_Z)) ^ 2$$
$$= (X - \mu_X)^2 + (Y - \mu_Y)^2 + (Z - \mu_Z)^2 + 
2((X - \mu_X)(Y - \mu_Y) + (X - \mu_X)(Z - \mu_Z) + (Y - \mu_Y)(Z - \mu_Z))$$

So taking the expected value of this, we get (by the addition rule):

$$E[(W - E[W])^2]$$
$$= var(X) + var(Y) + var(Z)
+ 2 E[(X - \mu_X)(Y - \mu_Y) + (X - \mu_X)(Z - \mu_Z) + (Y - \mu_Y)(Z - \mu_Z)]$$

Since $X$, $Y$, and $Z$ are independent, we can separate out each of the cross 
products, e.g., $E[(X - \mu_X)(Y - \mu_Y)] = E[X - \mu_X]E[Y - \mu_Y]$. But 
for each of the random variables, the expected value of the variable minus its 
expected value is just $0$, e.g., $E[X - \mu_X] = E[X] - \mu_X$ 
$= \mu_X - \mu_X = 0$. So all of the cross terms cancel out to $0$, and we're 
left with:

$$var(X + Y + Z) = E[(W - E[W])^2]$$
$$= var(X) + var(Y) + var(Z)$$

# Problem 3 (again?)

10" is $|\frac{10 - 21.88}{7.58}| \approx 1.567$ standard deviations from the 
mean.

## Part a

By Markov's inequality, we know that 
$P(|X - E[X]| \geq k \sigma_X) \leq \frac{1}{k^2}$. So if we want the 
probability that $X$ is more than 1.567 standard deviations from the mean, we 
can say that this probability is no more than $\frac{1}{1.567^2}$ 
$\approx 0.407$. In the extreme case where we have a heavily skewed 
distribution where the density more than 1.567 standard deviations above the 
mean is 0, all of 0.407 must be 1.567 standard deviations below the mean, so 
$\boxed{P(X \leq 10) \leq 0.407}$.

## Part b

On the other hand, if the distribution is symmetric about the mean, then 
half of this density is 1.567 standard deviations above the mean while 
half of it is 1.567 standard deviations below the mean. Then 
$\boxed{P(X \leq 10) \leq 0.204}$.

# Problem 4

## Part a

Let $N \sim poisson(\mu)$. We know that $E[N] = \mu$ and $var(N) = \mu$, so 
$E[N^2] = var(N) + E[N]^2 = \mu + \mu^2$.

Consider $E[N (N - 1) (N - 2)]$. This is equal to:

$$\sum_{i = 0} i (i-1) (i-2) e^{-\mu} \mu^i / i!$$
When $i \in \{0, 1, 2\}$, the corresponding terms are 0. So this is equal to:

$$\sum_{i = 3} i (i-1) (i-2) e^{-\mu} \mu^i / i!$$
Then 

$$= e^{-\mu} \mu^3 \sum_{i = 3} \mu^{i - 3} / (i - 3)!$$
$$= e^{-\mu} \mu^3 \sum_{i = 0} \mu^i / i!$$
$$= e^{-\mu} \mu^3 e^{\mu} = \mu^3$$.

On the other hand, this is equal to $E[N^3] - 3E[N^2] + 2E[N]$ after some 
expansion of the original term. So solving for $E[N^3]$:

$$E[N^3] = \mu^3 + 3 \mu^2 + \mu$$

If we expand $E[(X - Y)^3]$ and separate the cross terms using the fact that 
$X \perp Y$, we get:

$$E[X^3] - 3E[X^2]E[Y] + 3E[X]E[Y^2] - E[Y^3]$$

$E[X] = 2$, $E[X^2] = 2 + 2^2 = 6$, $E[X^3] = 2^3 + 3(2^2) + 2 = 22$

$E[Y] = 3$, $E[Y^2] = 3 + 3^2 = 12$, $E[Y^3] = 3^3 + 3(3^2) + 3 = 57$

So 

$$E[X^3] - 3E[X^2]E[Y] + 3E[X]E[Y^2] - E[Y^3]$$
$$= 22 - 3(6)(3) + 3(2)(12) - 57$$
$$= \boxed{-17}$$

## Part b

Since $X \perp Y$, $5X \perp Y$, so $var(5X + Y) = 25 var(X) + var(Y)$ 
$= 25 (2) + 3 = \boxed{53}$.

# Problem 5

This is equivalent to $P(\text{first two are face cards})$ 
$= \frac{12}{52} \frac{11}{51} = \boxed{\frac{1}{17}}$.

# Problem 6

## Part a

$P(RRB) = \frac{5}{7} \frac{4}{6} \frac{2}{5} = \boxed{\frac{4}{21}}$

## Part b

$P(BRB) = \frac{2}{7} \frac{5}{6} \frac{1}{5} = \boxed{\frac{1}{21}}$

## Part c

$P(RBB) = \frac{5}{7} \frac{2}{6} \frac{1}{5} = \boxed{\frac{1}{21}}$

## Part d

We can just sum up our answers from parts (a), (b), and (c):
$P(\text{third is } B) = \frac{4 + 1 + 1}{21} = \boxed{\frac{2}{7}}$

We also know that $P(\text{third is }B) = P(B) = \boxed{\frac{2}{7}}$.

# Problem 7

This is just the collector's problem. $E[X] = 10 \sum_i^{10} \frac{1}{i}$
$\approx \boxed{29.29}$.

# Problem 8

For this scenario, we need one out in the first seven bats, followed by two 
outs. So one possibility is out, not out six times, out, out. This has 
probability $p q^6 p p$ where $p = 0.6$ and $q = 0.4$. We can then see that 
all possibilities have the same probability $p^3 q^6$ and the first seven can be 
ordered however. Then there are $\binom{7}{1}$ possibilities. So 
$P(\text{2nd and 3rd outs are made by 8th and 9th players})$ 
$= \binom{7}{1} 0.6^3 0.4^6 \approx \boxed{6.193 \times 10^{-3}}$ We can also 
just think of this as $P(T_2 = 8)p$.