# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

search_algo <- function(y, X_covariates) {
    .Call(`_Stat676pack_search_algo`, y, X_covariates)
}

lm_mcmc_horseshoe <- function(y, X_covariates, N_sims, seed) {
    .Call(`_Stat676pack_lm_mcmc_horseshoe`, y, X_covariates, N_sims, seed)
}

