---
title: "STAT-S620"
subtitle: 'Assignment 1'
author: "John Koo"
output: pdf_document
# output: html_document
urlcolor: blue
header-includes:
- \usepackage{float}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      comment = NA, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.pos = 'H', 
                      fig.align = 'center', 
                      fig.height = 5, 
                      fig.width = 5)
options(xtable.comment = FALSE, 
        xtable.table.placement = 'H')
```

# Exercise 1.4.6

a. Blue card numbered 2 or 4
b. Blue card numbered 5-10
c. Any card numbered 1, 2, 3, 4, 6, 8, 10
d. Even-numbered blue card or red card numbered 2 or 4
e. Red card numbered 5, 7, 9

# Exercise 1.5.3

a. If $A$ and $B$ are disjoint, then $B \subset A^c$, so $P(B \cap A^c) = P(B)$
$= \boxed{\frac{1}{2}}$

b. If $A \subset B$ then $B \cap A^c$ is just $B \setminus A$ so $P(B \cap A^c)$
$= \frac{1}{2} - \frac{1}{3} = \boxed{\frac{1}{6}}$

c. $P(B \cap A^c) = P(B \setminus A) = \frac{1}{2} - \frac{1}{8} =
\boxed{\frac{3}{8}}$ 

# Exercise 1.5.8

Let $A$ be subscription to the morning paper and $B$ be subscription to the 
afternoon paper. $P(A) = .5$ and $P(B) = .65$ and $P(A \cup B) = .85$. Then 
$P(A \cap B) = .5 + .65 - .85 = \boxed{.3}$

# Exercise 1.6.5

Let $X_i$ be grade $i$. Then $P(X_i) = \frac{1}{7}$ for $i = 2, 3, 4, 5, 6$ and 
$P(X_1) = \frac{2}{7}$. We also assume that a student cannot be in two grades 
at once. Then $P(\text{odd numbered grade}) = \frac{2 + 1 + 1}{7}$
$= \boxed{\frac{4}{7}}$

# Exercise 1.6.8

a. Let $X = \{H, T\}$ and $Y = \{1, 2, 3, 4, 5, 6\}$. Then the sample space is 
$S = X \times Y = \{(H, 1), (T, 1), (H, 2), (T, 2), ...\}$, and $|S| = 12$.

b. If the coin and die are fair, then each outcome of $S$ is equally likely. 
The event of interest is $A = \{(H, 1), (H, 3), (H, 5)\}$, so 
$\frac{|A|}{|S|} = \frac{3}{12} = \boxed{\frac{1}{4}}$