---
title: "STAT-S620"
subtitle: 'Assignment 3'
author: "John Koo"
output: pdf_document
# output: html_document
urlcolor: blue
header-includes:
- \usepackage{float}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      comment = NA, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.pos = 'H', 
                      fig.align = 'center', 
                      fig.height = 5, 
                      fig.width = 5)
options(xtable.comment = FALSE, 
        xtable.table.placement = 'H')
```

# 2.1.9

## Part a

There are 4 cards left, 3 of which are red. Therefore, the probability is just 
$\boxed{\frac{3}{4}}$.

## Part b

Since all but one card are red, we are guaranteed to get at least one red card. 
Therefore, this is just the probability that both are red, which is 
$\frac{4}{5} \times \frac{3}{4} = \boxed{\frac{3}{5}}$.

# 2.1.14

$G$ : good working order  
$W$ : wearing down  
$N$ : needs maintenance

$D$ : defective
$D^c$: not defective

Then $P(D) = P(D|G) P(G) + P(D|W) P(W) + P(D|N) P(N)$ 
$= (.02)(.8) + (.1)(.1) + (.3)(.1)$
$= \boxed{`r .02 * .8 + .1 * .1 + .3 * .1`}$

# 2.2.6

$A$: win first lottery  
$B$: win second lottery

Then $P(A \cup B) = P(A) + P(B) - P(A \cap B) = P(A) + P(B) - P(A) P(B)$  
$= .01 + .02 - (.01)(.02) = \boxed{`r .01 + .02 - .01 * .02`}$

# 2.2.7

## Part a

$A$ : student $A$ is in class  
$B$ : student $B$ is in class

Then $P(A \cup B) = P(A) + P(B) - P(A) P(B)$ 
$= .8 + .6 - (.8) (.6) = \boxed{`r .8 + .6 - .8 * .6`}$

## Part b

$P(A | (A \cup B)) = \frac{P(A \cap (A \cup B))}{P(A \cup B)}$
$= \frac{P(A)}{P(A \cup B)} = .6 / .92 \approx \boxed{`r round(.6 / .92, 3)`}$

# 2.2.13

$P(X = 1) = \binom{10}{1} .01^1 .99^9$
$\approx \boxed{`r round(10 * .01 * .99 ** 9, 3)`}$

# 2.2.14

$P(X \geq 1) = 1 - P(X = 0) = 1 - .99^{10}$ 
$\approx \boxed{`r round(1 - .99 ** 10, 3)`}$

# 2.2.15

Find $n \in \mathbb{N}$ s.t. $1 - .99^n \geq .8$

Then $n = \lceil \frac{\log(.2)}{\log(.99)} \rceil$
$= \boxed{ `r ceiling(log(.2) / log(.99))`}$

# 2.3.4

$C$ denotes the event of having cancer. Then 
$P(C|+) = \frac{P(+|C)P(C)}{P(+|C)P(C) + P(+|C^c)P(C^c)} \approx$
$\boxed{`r round(1e-5 * .95 / (1e-5 * .95 + (1 - 1e-5) * .05), 4)`}$

# 2.3.13

## Part a

$F$ : coin is fair

We also have $P(F|HH) = \frac{1}{5}$ from an example in the text.

Then $P(F|HHH) = \frac{P(F|HH) P(H|FHH)}{P(F|HH) P(H|FHH) + P(F^c|HH) P(H|F^cHH)}$

If the coin is fair, then the probability of heads is $1/2$ regardless of the 
previous flips. If the coin is not fair, then the probability of heads is 1 
regardless of the previous flips. Then this is 
$P(F|HHH) = \frac{1/5 \times 1/2}{1/5 \times 1/2 + 4/5 \times 1}$
$= \boxed{\frac{1}{9}}$.

## Part b

If any coin flip lands tails, then it cannot be the biased coin. Therefore, 
$P(F|HHHT) = \boxed{1}$.

# 2.5.20

$P(B \text{ wins}) = P(B \text{ wins on second turn}) + 
P(B \text{ wins on fourth turn}) + ...$

We can see that $P(B \text{ wins on } i^{th} \text{ turn}) =$
$P(i - 1 \text{ failures}) P(\text{success})$ where $i = 1, 3, 5, ...$

$P(i-1 \text{ failures}) = \Pi_j^{i-1} P(\text{failure}) = \Pi_j^{i-1} 5/6$
$= (5/6)^{i-1}$. 

Then $P(B \text{ wins}) = \sum_{i=1} (5/6)^{2i-1} (1/6)$ 
$= (1/6)(5/6) \sum_{i=0} ((5/6)^2)^i = \frac{5/36}{1 - 25/36}$
$= \boxed{\frac{5}{11}}$.

# 2.5.24

$P(A|L) = \frac{P(L|A)P(A)}{P(L|A)P(A) + P(L|B)P(B) + P(L|C)P(C)}$
$= \boxed{\frac{1}{5}}$.